/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as FrotaRouteImport } from './routes/frota'
import { Route as TransfersIndexRouteImport } from './routes/transfers.index'
import { Route as TransfersRotaRouteImport } from './routes/transfers.$rota'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const FrotaRoute = FrotaRouteImport.update({
  id: '/frota',
  path: '/frota',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersIndexRoute = TransfersIndexRouteImport.update({
  id: '/transfers/',
  path: '/transfers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRotaRoute = TransfersRotaRouteImport.update({
  id: '/transfers/$rota',
  path: '/transfers/$rota',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/frota': typeof FrotaRoute
  '/transfers/$rota': typeof TransfersRotaRoute
  '/transfers/': typeof TransfersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/frota': typeof FrotaRoute
  '/transfers/$rota': typeof TransfersRotaRoute
  '/transfers': typeof TransfersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/frota': typeof FrotaRoute
  '/transfers/$rota': typeof TransfersRotaRoute
  '/transfers/': typeof TransfersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contato' | '/frota' | '/transfers/$rota' | '/transfers/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contato' | '/frota' | '/transfers/$rota' | '/transfers'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/frota'
    | '/transfers/$rota'
    | '/transfers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  FrotaRoute: typeof FrotaRoute
  TransfersRotaRoute: typeof TransfersRotaRoute
  TransfersIndexRoute: typeof TransfersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frota': {
      id: '/frota'
      path: '/frota'
      fullPath: '/frota'
      preLoaderRoute: typeof FrotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/': {
      id: '/transfers/'
      path: '/transfers'
      fullPath: '/transfers/'
      preLoaderRoute: typeof TransfersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/$rota': {
      id: '/transfers/$rota'
      path: '/transfers/$rota'
      fullPath: '/transfers/$rota'
      preLoaderRoute: typeof TransfersRotaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  FrotaRoute: FrotaRoute,
  TransfersRotaRoute: TransfersRotaRoute,
  TransfersIndexRoute: TransfersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
